name: publish

on:
  release:
    types:
      - released
  workflow_dispatch:

permissions:
  packages: write # For pushing to ghcr.io.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: robinraju/release-downloader@v1.5
        with:
          repository: "coder/code-marketplace"
          tag: ${{ github.ref_name }}
          fileName: "code-marketplace-linux-*"
          out-file-path: "bin"

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - run: docker buildx bake -f ./docker-bake.hcl --push
